Sample Data

In [19]:
import numpy as np
from sklearn import preprocessing

sample_data = np.array([[2.1, -1.9, 5.5], 
                        [-1.5, 2.4, 3.5], 
                        [0.5, -7.9, 5.6],
                        [5.9, 2.3, -5.8]])

sample_data

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

Import dataset numpy sebagai np karena datasetnya akan diset menjadi array
Module processing diimport dengan menggunakan sklearn 
Dataset dibentuk sebagai numpy array, dataset ini dipandang sebagai dataset feature yang dapat dilihat umlah barisnya ada 4.
Dataset ini terbagi kedalam 3 feature
Dataset yang terbentuk ini ditampung ke dalam variabel sample_data


In [17]:
sample_data.shape

(4, 3)

Untuk menampilkan dimensi dari datsaset dapat dilakukan dengan memanggil sample_data.shape

Binarisation

Untuk meghasilkan suatu data yang menghasilkan 2 nilai numerik, yaitu 0 dan 1. 

sample_data 

(untuk memanggil dataset yang sebelumnya)

In [20]:
preprocessor = preprocessing.Binarizer(threshold=0.5)
binarised_data = preprocessor.transform(sample_data)
binarised_data

array([[1., 0., 1.],
       [0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.]])

Membentuk objek binarizer dengan memanggil preprpcessing.Binarizer dengan menyertakan 1 buah parameter, yaitu threshold yang diset dengan nilai 0.5
Pemanggilan itu akan menghasilkan objek binarizer yang ditampung ke dalam variabel preprocessor
Tahapan selanjutnya adalah menggunakan transformasi terhadap sample data yang dimiliki dengan cara preprocessor.transform(sample_data)
Hasil transformasi ditampung ke dalam variabel binarised_data untuk menampilkan isinya
Hasil dari transformasi tersebut adalah mengkonfersikan nilai yang kurang dari 0.5 menjadi 0 dan nilai yang lebih besar dari 0.5 akan dikonfersikan menjadi nilai 1
Untuk nilai sebelumnya yang sama persis dengan nilai thresholdnya akan menjadi 0

Scaling
Untuk menghasilkan data numerik yang berada dalam rentang skala tertentu. 

sample_data
Untuk memanggil sample data sebelumnya yang terdiri dari nilai plotting point dari rentang -7.9 sebagai nilai terkecil samapi dengan nilai 5.9 sebagai nilai terbesarnya.

In [21]:
preprocessor = preprocessing.MinMaxScaler(feature_range=(0, 1))
preprocessor.fit(sample_data)
scaled_data = preprocessor.transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

Feature_range merupakan parameter yang memerlukan data yang akan memuat 2 nilai, yaitu 0 dan 1.
Nilai 0 akan mengidentifikasikan nilai terkecil dari skala terbaru dan nilai 1 mengidentifikasikan nilai terbesar dari skala terbaru.
Pemanggilan preprocessing.MinMaxScalerdengan nilai feature_range = 0,1 akan membentuk objek scaler yang akan ditampung dalam variabel processor
Objek scaler akan menggunakan method fit terhadap sample data yang kita miliki dengan cara 
preprocessor.fit_transform(sample_data). Setelah scaler di fit pada sample data, maka dapat digunakan untuk transformasi data
Hasil dari transformasi ditampung dalam variabel scaled_data yang kemudian akan menampilkan hasil dari scaled datanya

In [22]:
scaled_data = preprocessor.fit_transform(sample_data)
scaled_data

array([[0.48648649, 0.58252427, 0.99122807],
       [0.        , 1.        , 0.81578947],
       [0.27027027, 0.        , 1.        ],
       [1.        , 0.99029126, 0.        ]])

fit_transform adalah method penyatuan 2 proses, yaitu  fiting dan transormasi. Penggunaan method ini berarti proses fit dan transformasi dikenakan oleh data yang sama. Hasilnya akan ditampung oleh variabel scaled_data.

L1 Normalisation: Least Absolute Deviations

Untuk melakukan normalisasi terhadap data numerik yang dimiliki.

sample_data
Pemanggilan data set yang dimiliki.

In [23]:
l1_normalised_data = preprocessing.normalize(sample_data, norm='l1')
l1_normalised_data

array([[ 0.22105263, -0.2       ,  0.57894737],
       [-0.2027027 ,  0.32432432,  0.47297297],
       [ 0.03571429, -0.56428571,  0.4       ],
       [ 0.42142857,  0.16428571, -0.41428571]])

preprocessing.normalize akan membutuhkan 2 parameter, yaitu sample_data dan parameter norm =’l1’ yang akan berasosiasi dengan nilai absolute deviations yang akan menghasilkan data yang ternormalisasi. 
Data yang sudah ternormalisasi ditampung ke dalam variabel l1_normalisased_data yang akan menampilkan datanya.

L2 Normalisastion: Least Squares

In [24]:
sample_data 

array([[ 2.1, -1.9,  5.5],
       [-1.5,  2.4,  3.5],
       [ 0.5, -7.9,  5.6],
       [ 5.9,  2.3, -5.8]])

In [26]:
l2_normalised_data = preprocessing.normalize(sample_data, norm='l2')
l2_normalised_data

array([[ 0.33946114, -0.30713151,  0.88906489],
       [-0.33325106,  0.53320169,  0.7775858 ],
       [ 0.05156558, -0.81473612,  0.57753446],
       [ 0.68706914,  0.26784051, -0.6754239 ]])

Menyertakan 2 parameter, yaitu sample_data dan parameter norm =’l2’ akan berasosiasi dengan Least Squares. Pemanggilan fungsi akan menghasilkan data yang sudah ternormalisasi yang akan ditampung ke dalam variabel L2_normalised_data yang untuk selanjunya akan ditampilkan hasilnya.