In [1]:
from sklearn.datasets import load_boston

boston = load_boston()
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [2]:
boston.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [3]:
from sklearn import datasets
import pandas as pd

boston_data = datasets.load_boston()
df_boston = pd.DataFrame(boston_data.data,columns=boston_data.feature_names)
df_boston['target'] = pd.Series(boston_data.target)
df_boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

### Sample Dataset

In [4]:
import pandas as pd

rumah = {'jarak_rumah': [1, 2, 2, 3, 3],
         'pajak_rumah': [296, 242, 242, 222,222],
        'harga' : [24, 21.6, 34.7, 33.4, 36.2]}

rumah_df = pd.DataFrame(rumah)
rumah_df

jarak_rumah  pajak_rumah  harga
0            1          296   24.0
1            2          242   21.6
2            2          242   34.7
3            3          222   33.4
4            3          222   36.2

Import module pandas dengan memanggil import pandas as pd. Kemudian dilanjutkan dengan menyiapkan dictionary yang akan terdiri dari 3 buah case yaitu jarak rumah, pajak rumah, dan harga. Dictionary tersebut ditampung dalam sebuah variabel yang bernama rumah yang akan digunakan untuk pandas dataframe. Objek yang terbentuk pada data frame akan ditampung pada variable rumah_df. jarak rumah dan pajak rumah dalam kasus ini akan berperan sebagai features dan harga sebagai target.

### Features and Target

In [5]:
import numpy as np 

X_train = np.array(rumah_df[['jarak_rumah', 'pajak_rumah']])
y_train = np.array(rumah_df['harga'])

print(f'X_train:\n{X_train}\n')
print(f'y_train: {y_train}')

X_train:
[[  1 296]
 [  2 242]
 [  2 242]
 [  3 222]
 [  3 222]]

y_train: [24.  21.6 34.7 33.4 36.2]


Dalam kasus ini jarak rumah dan pajak rumah akan menggunakan numpy array yang ditampung dalam variabel X_train sebagai sekumpulan features untuk training set. Data harga menggunakan numpy array juga dengan menggunakan variabel y_train sebagai sekumpulan nilai target untuk training set.

### Training

In [6]:
from sklearn.neighbors import KNeighborsRegressor

K = 3
model = KNeighborsRegressor(n_neighbors=K)
model.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=3)

Untuk melakukan training maka harus mengimport KNeighborsRegressor terlebih dahulu

In [7]:
X_new = np.array([[2, 242]])
X_new

array([[  2, 242]])

In [8]:
y_pred = model.predict(X_new)
y_pred

#Memanggil model.predict yang berasal dari data yang sudah dibuat sebelumnya.

array([29.9])

### Evaluasi KNN Regression Model

In [17]:
X_test = np.array([[1, 296], [2, 242], [2, 242], [3, 222],[3, 222]])
y_test = np.array([26.8, 30.0, 30.0, 34.8, 34.8])

print(f'X_test:\n{X_test}\n')
print(f'y_test: {y_test}')

X_test:
[[  1 296]
 [  2 242]
 [  2 242]
 [  3 222]
 [  3 222]]

y_test: [26.8 30.  30.  34.8 34.8]


Pertama-tama harus menyiapkan testing set untuk nilai featuresnya untuk kemudian ditampung ke dalam variabel X_test. Kemudian sekumpulan nilai target ditampung ke dalam variabel y_test.

In [18]:
y_pred = model.predict(X_test)
y_pred

array([26.76666667, 29.9       , 29.9       , 34.76666667, 34.76666667])

Setelah melakukan testing set, langkah selanjutnya adalah melakukan prediksi dengan memanfaatkan model KNN Regression yang sudah ditraining sebelumnya, yaitu dengan memanggil X_test yang hasilnya akan ditampung dalam variabel y_pred.

### Coefficient of Determination atau R²

In [19]:
from sklearn.metrics import r2_score

r_squared = r2_score(y_test, y_pred)

print(f'R-squared: {r_squared}')

R-squared: 0.9995151817375887


Langkah pertama adalah dengan mengimport metrics r2_score kemudian langkah selanjutnya adalah dengan memanggil r2_score yang disertai oleh parameternya, yaitu y_test, y_pred yang ditampung dalam variabel r_squared. Nilai r2_square bila mendekati 1 dapat dinilai baik dan sebaliknya.Dalam kasus ini dinilai baik karena 0.9995151817375887 mendekati 1.

### Mean Absolute Error (MAE) atau Mean Absolute Deviation (MAD)


Merupakan nilai absolute error dari nilai rata-rata dan prediksi.

In [20]:
from sklearn.metrics import mean_absolute_error

MAE = mean_absolute_error(y_test, y_pred)

print(f'MAE : {MAE}')

MAE : 0.05999999999999801



$yi$ = merepresentasikan setiap nilai target pada testing set.

$\hat{y}_i$ = merepresentasikan nilai prediksi yang dihasilkan oleh model kita

Disini yang dihitung adalah selisih antara $yi$ dengan $\hat{y}_i$. Proses tersebut memungkinkan untuk menghasilkan nilai positif maupun nilai negatif. Jika hasil prediksinya ternyata lebih kecil dari nilai yang seharusnya, maka nilainya akan menjadi positif. Jika hasil prediksinya ternyata lebih besar dari nilai yang seharusnya, maka nilainya akan menjadi negatif. Untuk menghindari nilai negatif, maka kita harus menerapkan yang namanya absolute function. Absolute function ini akan menghilangkan nilai negatif artinya semua hasilnya, baik itu negatif maupun positif akan diubah menjadi nilai positif. Lalu berikutnya, selisih nilai ini akan diakumulasikan atau dijumlahkan untuk berikutnya kita akan bagi dengan 'n'. 'n' merepresentasikan jumlah data pointnya.

### Mean Squared Error (MSE) atau Mean Squared Deviation (MSD) 


MSE merupakan rata-rata dari error kuadrat untuk prediksi.

In [21]:
from sklearn.metrics import mean_squared_error

MSE = mean_squared_error(y_test, y_pred)

print(f'MSE : {MSE}')

MSE : 0.004666666666666421


$y_i$ merupakan nilai target dari testing set.

$\hat{y}_i$ merupakan nilai estimasi yang dihasilkan oleh model kita

Kedua nilai tersebut kita selisihkan yang dimana serupa dengan kasus sebelumnya, selisih kedua nilai terebut bisa postif dan juga bisa bernilai negatif. Jika ternyata nilai prediksinya lebih besar dari nilai sebenarnya, maka akan menghasilkan nilai negatif. Sedangkan jika nilai prediksinya lebih kecil dari nilai sebenarnya atau nilai ekspetasinya, maka akan menghasilkan nilai positif. Untuk menghindari nilai negatif pada $mse$, selisih nilainya akan kita pangkatkan 2. Lalu berikutnya, hasil pemangkata ini akan kita akumulasikan untuk kemudian kita bagi dengan 'n' yang diman 'n' merupakan jumlah untuk data pointnya.

### Dataset

#### Menerapkan Standard Scaler (Standard Score atau Z-Score)

$x$ : merepresentasikan nilai features.

$\bar{x}$ : merepresentasikan rata-rata nilai features.

$S$ : merepresentasikan nilai standard deviation dari sekumpulan nilai features.

$z$ : merepresentasikan nilai z-score.

In [23]:
import numpy as np
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

X_train = np.array([[1, 296], [1, 242], [2, 242], [3, 222], [3, 222]])
y_train = np.array([24., 21.6, 34.7, 33.4, 36.2])

X_test = np.array([[1, 296], [2, 242], [2, 242], [3, 222],[3, 222]])
y_test = np.array([26.8, 30.0, 30.0, 34.8, 34.8])

Pada training set disediakan X_train untuk menampung sekumpulan nilai features dan juga sekumpulan nilai target. Sedangkan pada Test set berisi sekumpulan nilai y_test features dan juga y_test terget.

### Features Scaling (Standaed Scaler)

In [26]:
X_train_scaled = ss.fit_transform(X_train)
X_test_scaled = ss.transform(X_test)

print(f'X_train_scaled:\n{X_train_scaled}\n')
print(f'X_test_scaled:\n{X_test_scaled}\n')

X_train_scaled:
[[-1.11803399  1.88807812]
 [-1.11803399 -0.10325427]
 [ 0.         -0.10325427]
 [ 1.11803399 -0.84078479]
 [ 1.11803399 -0.84078479]]

X_test_scaled:
[[-1.11803399  1.88807812]
 [ 0.         -0.10325427]
 [ 0.         -0.10325427]
 [ 1.11803399 -0.84078479]
 [ 1.11803399 -0.84078479]]



Langkah pertama adalah memanggil ss.fit_transform(X_train) yang kemudian ditampung pada variabel X_train_scaled. Kemudian juga memanggil ss.transform(X_test) yang ditampung pada variabek X_test_scaled.

### Training dan Evaluasi Model

In [27]:
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

MAE = mean_absolute_error(y_test, y_pred)
MSE = mean_squared_error(y_test, y_pred)

print(f'MAE: {MAE}')
print(f'MSE: {MSE}')

MAE: 0.05999999999999801
MSE: 0.004666666666666421


Objek modelnhya ditraining dengan menyertakan model.fit(X_train_scaled, y_train) sebagai parameternya. Setelah dilakukan training set, kemudian akan dilakukan prediksi dengan memanggil model.predict dan menyertakan (X_test_scaled) yang akan ditampung dalam variabel y_pred. Setelah itu akan dihitung nilai errornya dengan memanggil mean_absolute_errir(y_test, y_pred) yang ditampung pada variabel MAE. Sedangkan untum menghitung MSE caranya adalah dengan memanggil mean_squared_error(y_test, y_pred) yang ditampung dalam variabel MSE. Hasil dari MAE dan MSE dengan menggunakan features scalinh lebih baik dibandingkan dengan tidak menggunakannya karena hasik MSE dan MAE jauh lebih kecil dibandingkan sebelumnya.